<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>location_matching_20240409</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="location_matching_20240409_files/libs/clipboard/clipboard.min.js"></script>
<script src="location_matching_20240409_files/libs/quarto-html/quarto.js"></script>
<script src="location_matching_20240409_files/libs/quarto-html/popper.min.js"></script>
<script src="location_matching_20240409_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="location_matching_20240409_files/libs/quarto-html/anchor.min.js"></script>
<link href="location_matching_20240409_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="location_matching_20240409_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="location_matching_20240409_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="location_matching_20240409_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="location_matching_20240409_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">location_matching_20240409</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>Working with files from: <code>googledrive/VECTOR ATLAS/2024-03-14 - VA old but updata data for cleaning</code></p>
<p><img src="google_drive.png" class="img-fluid"></p>
<p>Matching locations missing in: <code>final_species.csv</code>,</p>
<p>from: <code>OLD MAP database dump/20210726_vector_extraction (1).csv</code></p>
<p>Packages</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(countrycode)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Read in data files and look at them:</p>
<section id="new-data-base" class="level5">
<h5 class="anchored" data-anchor-id="new-data-base">new data base</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>new_db <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">file =</span> <span class="st">"2024-03-14 - VA old but updated data for cleaning/final_species.csv"</span>,</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">guess_max =</span> <span class="dv">30000</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
Rows: 22150 Columns: 306
── Column specification
──────────────────────────────────────────────────────── Delimiter: "," chr
(147): MAP_DATA, MAP_NOTES, citation..DOI., author, article.title, journ... dbl
(115): ...1, X.1, X, bio_data, occ_data, source_ID, publication.year, la... lgl
(44): common.occupation_3, outdoor.activities.at.night, hours.spent.awa...
ℹ Use `spec()` to retrieve the full column specification for this data. ℹ
Specify the column types or set `show_col_types = FALSE` to quiet this message.
• `` -&gt; `...1`</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(new_db)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 22,150
Columns: 306
$ ...1                                                  &lt;dbl&gt; 18121, 5, 60, 62…
$ X.1                                                   &lt;dbl&gt; 29407, 3339, 925…
$ X                                                     &lt;dbl&gt; 29407, 3339, 925…
$ bio_data                                              &lt;dbl&gt; 0, 0, 0, 0, 0, 0…
$ occ_data                                              &lt;dbl&gt; 1, 1, 1, 1, 1, 1…
$ MAP_DATA                                              &lt;chr&gt; "NO", NA, NA, NA…
$ MAP_NOTES                                             &lt;chr&gt; NA, "Authors men…
$ source_ID                                             &lt;dbl&gt; 1050, 1462, 3248…
$ citation..DOI.                                        &lt;chr&gt; NA, "10.1186_147…
$ author                                                &lt;chr&gt; "Bockarie", "Cua…
$ article.title                                         &lt;chr&gt; "Malaria in a ru…
$ journal.title                                         &lt;chr&gt; "Ann Trop Med Pa…
$ publication.year                                      &lt;dbl&gt; 1994, 2006, 2008…
$ adult.data                                            &lt;chr&gt; "yes", "yes", "y…
$ larval.site.data                                      &lt;chr&gt; NA, NA, NA, NA, …
$ IR.data                                               &lt;chr&gt; "none", "genotyp…
$ study_sampling.design                                 &lt;chr&gt; "na", "na", "na"…
$ contact.authors                                       &lt;chr&gt; NA, NA, NA, NA, …
$ source.notes                                          &lt;chr&gt; NA, NA, NA, NA, …
$ country                                               &lt;chr&gt; "Sierra Leone", …
$ site                                                  &lt;chr&gt; "Nengbema,Nyande…
$ latitude_1                                            &lt;dbl&gt; 8.1340, -8.9833,…
$ longitude_1                                           &lt;dbl&gt; -11.6510, 13.250…
$ latitude_2                                            &lt;dbl&gt; 8.166, NA, NA, N…
$ longitude_2                                           &lt;dbl&gt; -11.484, NA, NA,…
$ latitude_3                                            &lt;dbl&gt; 8.2, NA, NA, NA,…
$ longitude_3                                           &lt;dbl&gt; -11.468, NA, NA,…
$ latitude_4                                            &lt;dbl&gt; 8.2, NA, NA, NA,…
$ longitude_4                                           &lt;dbl&gt; -11.501, NA, NA,…
$ latitude_5                                            &lt;dbl&gt; 8.117, NA, NA, N…
$ longitude_5                                           &lt;dbl&gt; -11.618, NA, NA,…
$ latitude_6                                            &lt;dbl&gt; NA, NA, NA, NA, …
$ longitude_6                                           &lt;dbl&gt; NA, NA, NA, NA, …
$ latitude_7                                            &lt;dbl&gt; NA, NA, NA, NA, …
$ longitude_7                                           &lt;dbl&gt; NA, NA, NA, NA, …
$ latitude_8                                            &lt;dbl&gt; NA, NA, NA, NA, …
$ longitude_8                                           &lt;dbl&gt; NA, NA, NA, NA, …
$ confidence.in.georef                                  &lt;chr&gt; NA, NA, NA, NA, …
$ GOOD_GUESS                                            &lt;chr&gt; "no", "no", "no"…
$ BAD_GUESS                                             &lt;chr&gt; "no", "no", "no"…
$ area.type                                             &lt;chr&gt; "wide area", "la…
$ georef.source                                         &lt;chr&gt; "*encarta", "com…
$ admin.level_1                                         &lt;chr&gt; "not specified",…
$ admin.level_2                                         &lt;chr&gt; "Bo district", N…
$ site.notes                                            &lt;chr&gt; "Results present…
$ insecticide.control                                   &lt;chr&gt; "n.a.", "n.a.", …
$ control.type                                          &lt;chr&gt; NA, NA, NA, NA, …
$ ITN.use                                               &lt;chr&gt; NA, NA, NA, NA, …
$ control.notes                                         &lt;chr&gt; NA, NA, NA, NA, …
$ sampling.method_1                                     &lt;chr&gt; "HLC - in", "Lar…
$ n_1                                                   &lt;dbl&gt; 0, 1, 1, 1, 1, 0…
$ sampling.method_2                                     &lt;chr&gt; "CDC-LT", NA, NA…
$ n_2                                                   &lt;dbl&gt; 1, NA, NA, NA, N…
$ sampling.method_3                                     &lt;chr&gt; "WinExit", NA, N…
$ n_3                                                   &lt;dbl&gt; 0, NA, NA, NA, N…
$ sampling.method_4                                     &lt;chr&gt; NA, NA, NA, NA, …
$ n_4                                                   &lt;dbl&gt; NA, NA, NA, NA, …
$ n_tot                                                 &lt;dbl&gt; 1, NA, 1, 1, 1, …
$ sampling.method.notes                                 &lt;chr&gt; "Human bait trap…
$ binary.presence                                       &lt;chr&gt; "yes", "yes", "y…
$ binary.absence                                        &lt;chr&gt; "no", "no", "no"…
$ abundance.data.in.a.graph                             &lt;chr&gt; "no", "no", "no"…
$ month_st                                              &lt;dbl&gt; 1, 4, 1, 4, 6, 6…
$ month_end                                             &lt;dbl&gt; 4, 4, 1, 4, 7, 9…
$ year_st                                               &lt;dbl&gt; 1990, 2001, 2004…
$ year_end                                              &lt;dbl&gt; 1991, 2001, 2004…
$ season..given.                                        &lt;chr&gt; "cross", NA, NA,…
$ season..calc.                                         &lt;chr&gt; NA, NA, NA, NA, …
$ rainfall_time                                         &lt;chr&gt; "2500 mm_year", …
$ season.notes                                          &lt;chr&gt; NA, NA, NA, NA, …
$ species                                               &lt;chr&gt; "abscurus", "ara…
$ SPECIES1                                              &lt;chr&gt; "abscurus", "GAM…
$ SPECIES2                                              &lt;chr&gt; "n.a.", "arabien…
$ species.notes                                         &lt;chr&gt; NA, NA, NA, NA, …
$ id_1                                                  &lt;chr&gt; "unknown", "gene…
$ id_2                                                  &lt;chr&gt; NA, "genetic_mol…
$ roof                                                  &lt;chr&gt; NA, NA, NA, NA, …
$ walls                                                 &lt;chr&gt; NA, NA, NA, NA, …
$ house.screening                                       &lt;chr&gt; NA, NA, NA, NA, …
$ open.eaves                                            &lt;chr&gt; NA, NA, NA, NA, …
$ cooking                                               &lt;chr&gt; NA, NA, NA, NA, …
$ housing.notes                                         &lt;chr&gt; NA, NA, NA, NA, …
$ common.occupation_1                                   &lt;chr&gt; NA, NA, NA, NA, …
$ common.occupation_2                                   &lt;chr&gt; NA, NA, NA, NA, …
$ common.occupation_3                                   &lt;lgl&gt; NA, NA, NA, NA, …
$ outdoor.activities.at.night                           &lt;lgl&gt; NA, NA, NA, NA, …
$ sleeping.outdoors                                     &lt;chr&gt; NA, NA, NA, NA, …
$ outdoor.timings_hours                                 &lt;chr&gt; NA, NA, NA, NA, …
$ outdoor.activities.notes                              &lt;chr&gt; NA, NA, NA, NA, …
$ average.bedtime                                       &lt;chr&gt; NA, NA, NA, NA, …
$ average.wake.time                                     &lt;chr&gt; NA, NA, NA, NA, …
$ time.people.leave.home..in.morning                    &lt;chr&gt; NA, NA, NA, NA, …
$ hours.spent.away.from.home.per.day                    &lt;lgl&gt; NA, NA, NA, NA, …
$ seasonal.labour                                       &lt;lgl&gt; NA, NA, NA, NA, …
$ community.notes                                       &lt;chr&gt; NA, NA, NA, NA, …
$ forest                                                &lt;chr&gt; "yes", NA, NA, N…
$ farming                                               &lt;chr&gt; NA, NA, NA, NA, …
$ farming.notes                                         &lt;chr&gt; NA, NA, NA, NA, …
$ livestock_1                                           &lt;chr&gt; "goats", NA, NA,…
$ livestock_2                                           &lt;chr&gt; "pigs", NA, NA, …
$ livestock_3                                           &lt;chr&gt; "dogs", NA, NA, …
$ livestock_4                                           &lt;chr&gt; "other", NA, NA,…
$ livestock.notes                                       &lt;chr&gt; "Sheep were also…
$ local.plants                                          &lt;chr&gt; NA, NA, NA, NA, …
$ environment.notes                                     &lt;chr&gt; NA, NA, NA, NA, …
$ sampling..biology._1                                  &lt;chr&gt; NA, NA, NA, NA, …
$ sampling..biology._2                                  &lt;chr&gt; NA, NA, NA, NA, …
$ sampling..biology._3                                  &lt;chr&gt; NA, NA, NA, NA, …
$ sampling..biology._n                                  &lt;chr&gt; NA, NA, NA, NA, …
$ parity..n.                                            &lt;dbl&gt; NA, NA, NA, NA, …
$ parity..total.                                        &lt;dbl&gt; NA, NA, NA, NA, …
$ parity..percent.                                      &lt;dbl&gt; NA, NA, NA, NA, …
$ daily.survival.rate..percent.                         &lt;dbl&gt; NA, NA, NA, NA, …
$ fecundity..mean.batch.size.                           &lt;dbl&gt; NA, NA, NA, NA, …
$ gonotrophic.cycle..days.                              &lt;dbl&gt; NA, NA, NA, NA, …
$ biology.notes                                         &lt;chr&gt; NA, NA, NA, NA, …
$ sampling..infection._1                                &lt;chr&gt; NA, NA, NA, NA, …
$ sampling..infection._2                                &lt;chr&gt; NA, NA, NA, NA, …
$ sampling..infection._3                                &lt;chr&gt; NA, NA, NA, NA, …
$ sampling..infection._n                                &lt;chr&gt; NA, NA, NA, NA, …
$ SR.by.dissection..n.                                  &lt;dbl&gt; NA, NA, NA, NA, …
$ SR.by.dissection..total.                              &lt;dbl&gt; NA, NA, NA, NA, …
$ SR.by.dissection..percent.                            &lt;dbl&gt; NA, NA, NA, NA, …
$ SR.by.CSP..n_pool.                                    &lt;chr&gt; NA, NA, NA, NA, …
$ SR.by.CSP..total_pool.                                &lt;chr&gt; NA, NA, NA, NA, …
$ SR.by.CSP.percent.                                    &lt;dbl&gt; NA, NA, NA, NA, …
$ SR.by.Pf..n.                                          &lt;dbl&gt; NA, NA, NA, NA, …
$ SR.by.Pf..total.                                      &lt;dbl&gt; NA, NA, NA, NA, …
$ SR.by.P..falciparum                                   &lt;dbl&gt; NA, NA, NA, NA, …
$ SR.by.Pv..n.                                          &lt;lgl&gt; NA, NA, NA, NA, …
$ SR.by.Pv..total.                                      &lt;lgl&gt; NA, NA, NA, NA, …
$ SR.by.P..vivax                                        &lt;lgl&gt; NA, NA, NA, NA, …
$ oocyst..n.                                            &lt;dbl&gt; NA, NA, NA, NA, …
$ oocyst..total.                                        &lt;dbl&gt; NA, NA, NA, NA, …
$ oocyst.rate..percent.                                 &lt;dbl&gt; NA, NA, NA, NA, …
$ EIR                                                   &lt;dbl&gt; NA, NA, NA, NA, …
$ EIR..period.                                          &lt;chr&gt; NA, NA, NA, NA, …
$ Ext..incubation.period..days.                         &lt;dbl&gt; NA, NA, NA, NA, …
$ infection.notes                                       &lt;chr&gt; NA, NA, NA, NA, …
$ HBR.sampling..indoor.                                 &lt;chr&gt; NA, NA, NA, NA, …
$ indoor.HBR                                            &lt;dbl&gt; NA, NA, NA, NA, …
$ HBR.sampling..outdoor.                                &lt;chr&gt; NA, NA, NA, NA, …
$ outdoor.HBR                                           &lt;dbl&gt; NA, NA, NA, NA, …
$ HBR.sampling..combined._1                             &lt;chr&gt; NA, NA, NA, NA, …
$ HBR.sampling..combined._2                             &lt;chr&gt; NA, NA, NA, NA, …
$ HBR.sampling..combined._3                             &lt;chr&gt; NA, NA, NA, NA, …
$ HBR.sampling..combined._n                             &lt;lgl&gt; NA, NA, NA, NA, …
$ combined.HBR                                          &lt;dbl&gt; NA, NA, NA, NA, …
$ HBR..unit.                                            &lt;chr&gt; NA, NA, NA, NA, …
$ ABR.sampling_1                                        &lt;lgl&gt; NA, NA, NA, NA, …
$ ABR.sampling_2                                        &lt;lgl&gt; NA, NA, NA, NA, …
$ ABR.sampling_3                                        &lt;lgl&gt; NA, NA, NA, NA, …
$ ABR.sampling_n                                        &lt;lgl&gt; NA, NA, NA, NA, …
$ ABR                                                   &lt;lgl&gt; NA, NA, NA, NA, …
$ ABR.unit                                              &lt;lgl&gt; NA, NA, NA, NA, …
$ biting.rate.notes                                     &lt;chr&gt; NA, NA, NA, NA, …
$ host.sampling..indoor.                                &lt;chr&gt; NA, NA, NA, NA, …
$ indoor.host..n.                                       &lt;dbl&gt; NA, NA, NA, NA, …
$ indoor.host..total.                                   &lt;dbl&gt; NA, NA, NA, NA, …
$ indoor.host.percent                                   &lt;dbl&gt; NA, NA, NA, NA, …
$ host.sampling..outdoor.                               &lt;chr&gt; NA, NA, NA, NA, …
$ outdoor.host..n.                                      &lt;dbl&gt; NA, NA, NA, NA, …
$ outdoor.host..total.                                  &lt;dbl&gt; NA, NA, NA, NA, …
$ outdoor.host..percent.                                &lt;dbl&gt; NA, NA, NA, NA, …
$ host.sampling..combined._1                            &lt;chr&gt; NA, NA, NA, NA, …
$ host.sampling..combined._2                            &lt;chr&gt; NA, NA, NA, NA, …
$ host.sampling..combined._3                            &lt;chr&gt; NA, NA, NA, NA, …
$ host.sampling..combined._n                            &lt;chr&gt; NA, NA, NA, NA, …
$ combined.host..n.                                     &lt;dbl&gt; NA, NA, NA, NA, …
$ combined.host..total.                                 &lt;dbl&gt; NA, NA, NA, NA, …
$ combined.host                                         &lt;dbl&gt; NA, NA, NA, NA, …
$ host..unit.                                           &lt;chr&gt; NA, NA, NA, NA, …
$ host.sampling..other._1                               &lt;chr&gt; NA, NA, NA, NA, …
$ host.sampling..other._2                               &lt;lgl&gt; NA, NA, NA, NA, …
$ host.sampling..other._3                               &lt;lgl&gt; NA, NA, NA, NA, …
$ host.sampling..other._n                               &lt;chr&gt; NA, NA, NA, NA, …
$ other.host..n.                                        &lt;chr&gt; NA, NA, NA, NA, …
$ other.host..total.                                    &lt;dbl&gt; NA, NA, NA, NA, …
$ host..other.                                          &lt;dbl&gt; NA, NA, NA, NA, …
$ host..other..unit                                     &lt;chr&gt; NA, NA, NA, NA, …
$ host.notes                                            &lt;chr&gt; NA, NA, NA, NA, …
$ biting....No..of.sampling.nights..indoors.            &lt;dbl&gt; NA, NA, NA, NA, …
$ biting.sampling..indoor.                              &lt;chr&gt; NA, NA, NA, NA, …
$ indoor.biting..n.                                     &lt;dbl&gt; NA, NA, NA, NA, …
$ indoor.biting..total.                                 &lt;dbl&gt; NA, NA, NA, NA, …
$ indoor.biting.data                                    &lt;dbl&gt; NA, NA, NA, NA, …
$ biting....No..of.sampling.nights..outdoors.           &lt;dbl&gt; NA, NA, NA, NA, …
$ biting.sampling..outdoor.                             &lt;chr&gt; NA, NA, NA, NA, …
$ outdoor.biting..n.                                    &lt;dbl&gt; NA, NA, NA, NA, …
$ outdoor.biting..total.                                &lt;dbl&gt; NA, NA, NA, NA, …
$ outdoor.biting.data                                   &lt;dbl&gt; NA, NA, NA, NA, …
$ indoor_outdoor.biting..unit.                          &lt;chr&gt; NA, NA, NA, NA, …
$ indoor_outdoor.biting.notes                           &lt;chr&gt; NA, NA, NA, NA, …
$ biting.activity..indoor......No..of.sampling.nights   &lt;dbl&gt; NA, NA, NA, NA, …
$ X18.00.19.00..in.                                     &lt;dbl&gt; NA, NA, NA, NA, …
$ X19.00.20.00..in.                                     &lt;dbl&gt; NA, NA, NA, NA, …
$ X20.00.21.00..in.                                     &lt;dbl&gt; NA, NA, NA, NA, …
$ X21.00.22.00..in.                                     &lt;dbl&gt; NA, NA, NA, NA, …
$ X22.00.23.00..in.                                     &lt;dbl&gt; NA, NA, NA, NA, …
$ X23.00.00.00..in.                                     &lt;dbl&gt; NA, NA, NA, NA, …
$ X00.00.01.00..in.                                     &lt;dbl&gt; NA, NA, NA, NA, …
$ X01.00.02.00..in.                                     &lt;dbl&gt; NA, NA, NA, NA, …
$ X02.00.03.00..in.                                     &lt;dbl&gt; NA, NA, NA, NA, …
$ X03.00.04.00..in.                                     &lt;dbl&gt; NA, NA, NA, NA, …
$ X04.00.05.00..in.                                     &lt;dbl&gt; NA, NA, NA, NA, …
$ X05.00.06.00..in.                                     &lt;dbl&gt; NA, NA, NA, NA, …
$ X18.30.21.30..in.                                     &lt;lgl&gt; NA, NA, NA, NA, …
$ X21.30.00.30..in.                                     &lt;lgl&gt; NA, NA, NA, NA, …
$ X00.30.03.30..in.                                     &lt;lgl&gt; NA, NA, NA, NA, …
$ X03.30.06.30..in.                                     &lt;lgl&gt; NA, NA, NA, NA, …
$ biting.activity..outdoor......No..of.sampling.nights  &lt;dbl&gt; NA, NA, NA, NA, …
$ X18.00.19.00..out.                                    &lt;lgl&gt; NA, NA, NA, NA, …
$ X19.00.20.00..out.                                    &lt;dbl&gt; NA, NA, NA, NA, …
$ X20.00.21.00..out.                                    &lt;dbl&gt; NA, NA, NA, NA, …
$ X21.00.22.00..out.                                    &lt;dbl&gt; NA, NA, NA, NA, …
$ X22.00.23.00..out.                                    &lt;dbl&gt; NA, NA, NA, NA, …
$ X23.00.00.00..out.                                    &lt;dbl&gt; NA, NA, NA, NA, …
$ X00.00.01.00..out.                                    &lt;dbl&gt; NA, NA, NA, NA, …
$ X01.00.02.00..out.                                    &lt;dbl&gt; NA, NA, NA, NA, …
$ X02.00.03.00..out.                                    &lt;dbl&gt; NA, NA, NA, NA, …
$ X03.00.04.00..out.                                    &lt;dbl&gt; NA, NA, NA, NA, …
$ X04.00.05.00..out.                                    &lt;lgl&gt; NA, NA, NA, NA, …
$ X05.00.06.00..out.                                    &lt;lgl&gt; NA, NA, NA, NA, …
$ X18.30.21.30..out.                                    &lt;lgl&gt; NA, NA, NA, NA, …
$ X21.30.00.30..out.                                    &lt;lgl&gt; NA, NA, NA, NA, …
$ X00.30.03.30..out.                                    &lt;lgl&gt; NA, NA, NA, NA, …
$ X03.30.06.30..out.                                    &lt;lgl&gt; NA, NA, NA, NA, …
$ biting.activity..combined......No..of.sampling.nights &lt;dbl&gt; NA, NA, NA, NA, …
$ X18.00.19.00..combined.                               &lt;lgl&gt; NA, NA, NA, NA, …
$ X19.00.20.00..combined.                               &lt;lgl&gt; NA, NA, NA, NA, …
$ X20.00.21.00..combined.                               &lt;lgl&gt; NA, NA, NA, NA, …
$ X21.00.22.00..combined.                               &lt;lgl&gt; NA, NA, NA, NA, …
$ X22.00.23.00..combined.                               &lt;dbl&gt; NA, NA, NA, NA, …
$ X23.00.00.00..combined.                               &lt;dbl&gt; NA, NA, NA, NA, …
$ X00.00.01.00..combined.                               &lt;dbl&gt; NA, NA, NA, NA, …
$ X01.00.02.00..combined.                               &lt;dbl&gt; NA, NA, NA, NA, …
$ X02.00.03.00..combined.                               &lt;dbl&gt; NA, NA, NA, NA, …
$ X03.00.04.00..combined.                               &lt;dbl&gt; NA, NA, NA, NA, …
$ X04.00.05.00..combined.                               &lt;lgl&gt; NA, NA, NA, NA, …
$ X05.00.06.00..combined.                               &lt;chr&gt; NA, NA, NA, NA, …
$ X18.30.21.30..combined.                               &lt;lgl&gt; NA, NA, NA, NA, …
$ X21.30.00.30..combined.                               &lt;dbl&gt; NA, NA, NA, NA, …
$ X00.30.03.30..combined.                               &lt;lgl&gt; NA, NA, NA, NA, …
$ X03.30.06.30..combined.                               &lt;lgl&gt; NA, NA, NA, NA, …
$ biting.notes                                          &lt;chr&gt; NA, NA, NA, NA, …
$ resting.sampling..indoor.                             &lt;chr&gt; NA, NA, NA, NA, …
$ unfed..indoor.                                        &lt;dbl&gt; NA, NA, NA, NA, …
$ fed..indoor.                                          &lt;dbl&gt; NA, NA, NA, NA, …
$ gravid..indoor.                                       &lt;dbl&gt; NA, NA, NA, NA, …
$ total..indoor.                                        &lt;dbl&gt; NA, NA, NA, NA, …
$ resting.sampling..outdoor.                            &lt;chr&gt; NA, NA, NA, NA, …
$ unfed..outdoor.                                       &lt;dbl&gt; NA, NA, NA, NA, …
$ fed..outdoor.                                         &lt;dbl&gt; NA, NA, NA, NA, …
$ gravid..outdoor.                                      &lt;dbl&gt; NA, NA, NA, NA, …
$ total..outdoor.                                       &lt;dbl&gt; NA, NA, NA, NA, …
$ resting.sampling..other.                              &lt;chr&gt; NA, NA, NA, NA, …
$ unfed..other.                                         &lt;dbl&gt; NA, NA, NA, NA, …
$ fed..other.                                           &lt;dbl&gt; NA, NA, NA, NA, …
$ gravid..other.                                        &lt;dbl&gt; NA, NA, NA, NA, …
$ total..other.                                         &lt;dbl&gt; NA, NA, NA, NA, …
$ resting..unit.                                        &lt;chr&gt; NA, NA, NA, NA, …
$ resting.notes                                         &lt;chr&gt; NA, NA, NA, NA, …
$ larval.habitat_1                                      &lt;chr&gt; NA, NA, NA, NA, …
$ LH.1_site.character                                   &lt;chr&gt; NA, NA, NA, NA, …
$ LH.1_turbidity                                        &lt;chr&gt; NA, NA, NA, NA, …
$ LH.1_salinity                                         &lt;chr&gt; NA, NA, NA, NA, …
$ LH.1_vegetation                                       &lt;chr&gt; NA, NA, NA, NA, …
$ LH.1_shade                                            &lt;chr&gt; NA, NA, NA, NA, …
$ LH.1_water.current                                    &lt;chr&gt; NA, NA, NA, NA, …
$ LH.1_size..diameter_widest.point.                     &lt;chr&gt; NA, NA, NA, NA, …
$ LH.1_depth                                            &lt;chr&gt; NA, NA, NA, NA, …
$ LH.1_permanence                                       &lt;chr&gt; NA, NA, NA, NA, …
$ LH.1_other.fauna                                      &lt;chr&gt; NA, NA, NA, NA, …
$ LH.1_larval.control.present                           &lt;chr&gt; NA, NA, NA, NA, …
$ larval.habitat_2                                      &lt;chr&gt; NA, NA, NA, NA, …
$ LH.2_site.character                                   &lt;chr&gt; NA, NA, NA, NA, …
$ LH.2_turbididity                                      &lt;lgl&gt; NA, NA, NA, NA, …
$ LH.2_salinity                                         &lt;lgl&gt; NA, NA, NA, NA, …
$ LH.2_vegetation                                       &lt;chr&gt; NA, NA, NA, NA, …
$ LH.2_shade                                            &lt;chr&gt; NA, NA, NA, NA, …
$ LH.2_water.current                                    &lt;lgl&gt; NA, NA, NA, NA, …
$ LH.2_size                                             &lt;chr&gt; NA, NA, NA, NA, …
$ LH.2_depth                                            &lt;chr&gt; NA, NA, NA, NA, …
$ LH.2_permenance                                       &lt;chr&gt; NA, NA, NA, NA, …
$ LH.2_other.fauna                                      &lt;chr&gt; NA, NA, NA, NA, …
$ LH.2_larval.control.present                           &lt;chr&gt; NA, NA, NA, NA, …
$ Larval.habitat_3                                      &lt;chr&gt; NA, NA, NA, NA, …
$ LH.1_site.character_3                                 &lt;chr&gt; NA, NA, NA, NA, …
$ LH.3_turbidity                                        &lt;chr&gt; NA, NA, NA, NA, …
$ LH.3_salinity                                         &lt;lgl&gt; NA, NA, NA, NA, …
$ LH.3_vegetation                                       &lt;chr&gt; NA, NA, NA, NA, …
$ LH.3_shade                                            &lt;lgl&gt; NA, NA, NA, NA, …
$ LH.3_water.current                                    &lt;lgl&gt; NA, NA, NA, NA, …
$ LH.3_size                                             &lt;chr&gt; NA, NA, NA, NA, …
$ LH.3_depth                                            &lt;chr&gt; NA, NA, NA, NA, …
$ LH.3_other.fauna                                      &lt;chr&gt; NA, NA, NA, NA, …
$ LH.3_larval.control.present                           &lt;lgl&gt; NA, NA, NA, NA, …
$ larval.notes                                          &lt;chr&gt; NA, NA, NA, NA, …
$ data.abstracted.by                                    &lt;chr&gt; NA, "LC", "LC", …
$ data.checked.by                                       &lt;chr&gt; NA, "DNN", "DNN"…
$ final.check                                           &lt;chr&gt; NA, NA, NA, NA, …
$ anopheline_region_id                                  &lt;lgl&gt; NA, NA, NA, NA, …
$ anopheline_taxonomic_level                            &lt;lgl&gt; NA, NA, NA, NA, …
$ Larval.notes                                          &lt;chr&gt; NA, NA, NA, NA, …
$ Larval.site.notes                                     &lt;chr&gt; NA, NA, NA, NA, …
$ continent                                             &lt;chr&gt; "Africa", "Afric…</code></pre>
</div>
</div>
</section>
<section id="old-data-dump" class="level4">
<h4 class="anchored" data-anchor-id="old-data-dump">old data dump</h4>
<p>read in, and get rid of non-African sites</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>old_db <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">file =</span> <span class="st">"2024-03-14 - VA old but updated data for cleaning/OLD MAP database dump/20210726_vector_extraction (1).csv"</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>( <span class="co"># assign a continent based on the 3-letter country ID</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    <span class="co"># some vector_site_country entries are blank, but the ID is not</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">continent =</span> <span class="fu">countrycode</span>(</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>      vector_site_country_id,</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>      <span class="st">"iso3c"</span>,</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>      <span class="st">"continent"</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(continent <span class="sc">==</span> <span class="st">"Africa"</span>) <span class="sc">|&gt;</span> <span class="co"># only keep African countries</span></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>continent) <span class="co"># remove this column from the database</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 198490 Columns: 70
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (37): sample_period_assi, collection_method_name, collection_method_abbr...
dbl (23): sample_period_id, sample_period_month_start, sample_period_year_st...
lgl (10): anopheline_is_dvs, vector_site_bestguess_good, vector_site_bestgue...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(old_db)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 39,119
Columns: 70
$ sample_period_id                         &lt;dbl&gt; 2277, 2277, 2278, 2278, 2278,…
$ sample_period_month_start                &lt;dbl&gt; 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,…
$ sample_period_year_start                 &lt;dbl&gt; 1994, 1994, 1994, 1994, 1994,…
$ sample_period_month_end                  &lt;dbl&gt; 12, 12, 12, 12, 12, 12, 12, 1…
$ sample_period_year_end                   &lt;dbl&gt; 1994, 1994, 1994, 1994, 1994,…
$ sample_period_assi                       &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, N…
$ sample_period_control_type_id            &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, N…
$ collection_id                            &lt;dbl&gt; 6525, 6525, 6526, 6527, 6528,…
$ collection_ordinal                       &lt;dbl&gt; 1, 1, 1, 2, 3, 4, 1, 1, 2, 2,…
$ collection_method_id                     &lt;dbl&gt; 9, 9, 12, 13, 6, 19, 12, 12, …
$ collection_count                         &lt;dbl&gt; 616, 616, NA, NA, NA, NA, NA,…
$ collection_method_name                   &lt;chr&gt; "larval collection", "larval …
$ collection_method_abbreviation           &lt;chr&gt; "l", "l", "mbi", "mbo", "hri"…
$ identification_ordinal                   &lt;dbl&gt; 1, 2, 1, 1, 1, 1, 1, 2, 1, 2,…
$ identification_method_name               &lt;chr&gt; "morphology", "chromosomal ba…
$ identification_method_abbreviation       &lt;chr&gt; "m", "cbs", "m", "m", "m", "m…
$ control_method_name                      &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, N…
$ control_method_abbreviation              &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, N…
$ sample_period_sample_aggregate           &lt;dbl&gt; 616, 616, 10, 10, 10, 10, 116…
$ sample_period_notes                      &lt;chr&gt; NA, NA, "Paper also gives mor…
$ anopheline_id                            &lt;dbl&gt; 7, 7, 23, 23, 23, 23, 7, 7, 7…
$ anopheline_name                          &lt;chr&gt; "&lt;i&gt;Anopheles arabiensis&lt;/i&gt; …
$ anopheline_sub_genus                     &lt;chr&gt; "Cellia", "Cellia", "Cellia",…
$ anopheline_species                       &lt;chr&gt; "arabiensis", "arabiensis", "…
$ anopheline_abbreviation                  &lt;chr&gt; "arabiensis", "arabiensis", "…
$ anopheline_author                        &lt;chr&gt; "Patton, 1905", "Patton, 1905…
$ anopheline_parent_id                     &lt;dbl&gt; 54, 54, NA, NA, NA, NA, 54, 5…
$ anopheline_scientific_name               &lt;chr&gt; "&lt;i&gt;Anopheles&lt;/i&gt; (&lt;i&gt;Cellia&lt;…
$ anopheline_taxonomic_level               &lt;chr&gt; "species", "species", "specie…
$ anopheline_region_id                     &lt;chr&gt; "Africa", "Africa", "Africa",…
$ anopheline_scientific_abbr               &lt;chr&gt; "&lt;i&gt;An. arabiensis&lt;/i&gt;", "&lt;i&gt;…
$ anopheline_is_dvs                        &lt;lgl&gt; TRUE, TRUE, TRUE, TRUE, TRUE,…
$ anophenline_taxonomic_level              &lt;chr&gt; "species", "species", "specie…
$ anopheline_reboot_id                     &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, N…
$ anopheline_reboot_parent                 &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, N…
$ anopheline_reboot_species                &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, N…
$ anopheline_reboot_full_name              &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, N…
$ anopheline_reboot_species_alternate      &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, N…
$ anopheline_reboot_full_name_alternate    &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, N…
$ anopheline_reboot_sub_genus              &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, N…
$ vector_site_id                           &lt;dbl&gt; 28821, 28821, 28821, 28821, 2…
$ vector_site_coordinates_name             &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, N…
$ vector_site_coordinates_ordinal          &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,…
$ vector_site_coordinates_latitude         &lt;dbl&gt; 7.984, 7.984, 7.984, 7.984, 7…
$ vector_site_coordinates_longitude        &lt;dbl&gt; 38.716, 38.716, 38.716, 38.71…
$ vector_site_admin2_id                    &lt;dbl&gt; 13728, 13728, 13728, 13728, 1…
$ vector_site_full_name                    &lt;chr&gt; "Eddo Kontola (Zwai Area)", "…
$ vector_site_latlong_source               &lt;chr&gt; "Combination", "Combination",…
$ vector_site_bestguess_good               &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, N…
$ vector_site_bestguess_rough              &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, N…
$ vector_site_admin1_paper                 &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, N…
$ vector_site_admin2_paper                 &lt;chr&gt; "Eastern Shoa Zone", "Eastern…
$ vector_site_admin3_paper                 &lt;chr&gt; "Adami Tulu District", "Adami…
$ vector_site_vector_site_notes            &lt;chr&gt; "Rift Valley", "Rift Valley",…
$ vector_site_notes                        &lt;chr&gt; "Descirption in report + Enca…
$ vector_site_forest                       &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, F…
$ vector_site_rice                         &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, F…
$ vector_site_country                      &lt;chr&gt; "Ethiopia", "Ethiopia", "Ethi…
$ vector_site_has_vector_data              &lt;lgl&gt; TRUE, TRUE, TRUE, TRUE, TRUE,…
$ vector_site_has_geometry                 &lt;lgl&gt; TRUE, TRUE, TRUE, TRUE, TRUE,…
$ vector_site_admin_id                     &lt;dbl&gt; 13763, 13763, 13763, 13763, 1…
$ vector_site_country_id                   &lt;chr&gt; "ETH", "ETH", "ETH", "ETH", "…
$ vector_site_area_type                    &lt;chr&gt; "point", "point", "point", "p…
$ vector_site_rural_urban                  &lt;chr&gt; "rural", "rural", "rural", "r…
$ source_id                                &lt;dbl&gt; 351, 351, 351, 351, 351, 351,…
$ source_citation                          &lt;chr&gt; "Abose, T. (1998). &lt;i&gt;Re-orie…
$ sample_period_complex                    &lt;chr&gt; "n.a.", "n.a.", "n.a.", "n.a.…
$ sample_period_tag_recommended_unreliable &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, F…
$ sample_period_is_copy                    &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, F…
$ sample_period_asia_2016_dataset          &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, F…</code></pre>
</div>
</div>
<p>Get site data from old database. This is unique combinations of site id, site name, latitude, and longitude</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>old_sites <span class="ot">&lt;-</span> old_db <span class="sc">|&gt;</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>    <span class="co">#id = vector_site_id,</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">site =</span> vector_site_full_name,</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">lat =</span> vector_site_coordinates_latitude,</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">lon =</span> vector_site_coordinates_longitude</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>()</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>old_sites</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2,444 × 3
   site                       lat   lon
   &lt;chr&gt;                    &lt;dbl&gt; &lt;dbl&gt;
 1 Eddo Kontola (Zwai Area)  7.98  38.7
 2 Kwameta                  -5.11  38.5
 3 Magundi                  -5.09  38.5
 4 Kwamhanya                -5.06  38.5
 5 Bagamoyo                 -5.07  38.4
 6 Balangai                 -4.93  38.4
 7 Ebolakounou               3.93  12.1
 8 Koundou                   3.9   12.1
 9 Labe                     11.3  -12.3
10 Sombili                  11.5  -12.5
# ℹ 2,434 more rows</code></pre>
</div>
</div>
<p>There are 2444 unique combinations. However, some site names correspond to &gt;1 set of coordinates or vice versa, as there are fewer unique site names than site IDs, and no site names are missing:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">unique</span>(old_sites<span class="sc">$</span>site)) <span class="co"># number of unique site names</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1904</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(old_sites<span class="sc">$</span>site)) <span class="co"># number of missing site names</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p>Let’s find the duplicated names, and check for duplicated coordinates. Here are all the sites with either duplicated names or duplicated coordinates</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>old_dup <span class="ot">&lt;-</span> old_sites <span class="sc">|&gt;</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(site) <span class="sc">|&gt;</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">unique_site =</span> <span class="fu">n</span>(),</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">unique_site =</span> <span class="fu">ifelse</span>(unique_site <span class="sc">==</span> <span class="dv">1</span>, <span class="cn">TRUE</span>, <span class="cn">FALSE</span>)</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span> () <span class="sc">|&gt;</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(lon, lat) <span class="sc">|&gt;</span></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">unique_coords =</span> <span class="fu">n</span>(),</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">unique_coords =</span> <span class="fu">ifelse</span>(unique_coords <span class="sc">==</span> <span class="dv">1</span>, <span class="cn">TRUE</span>, <span class="cn">FALSE</span>)</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>unique_site <span class="sc">|</span> <span class="sc">!</span>unique_coords) <span class="sc">|&gt;</span></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(site)</span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>old_dup</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,070 × 5
# Groups:   lon, lat [914]
   site                                    lat     lon unique_site unique_coords
   &lt;chr&gt;                                 &lt;dbl&gt;   &lt;dbl&gt; &lt;lgl&gt;       &lt;lgl&gt;        
 1 3 Rice Field Districts in Bouake Ci…  7.69   -5.03  TRUE        FALSE        
 2 3 villages (Diomandou Walo, Diomand… 16.5   -14.4   TRUE        FALSE        
 3 4 contiguous villages near Asembo    -0.183  34.4   TRUE        FALSE        
 4 Abia                                  5.72    0.133 FALSE       TRUE         
 5 Abia                                  5.72    0.132 FALSE       TRUE         
 6 Abia                                  5.72   -0.133 FALSE       TRUE         
 7 Abidjan                               5.33   -4.03  FALSE       TRUE         
 8 Abidjan                               5.33   -4.03  FALSE       TRUE         
 9 Abidjan                               5.34   -4.03  FALSE       TRUE         
10 Abuda                                15.4    36.5   TRUE        FALSE        
# ℹ 1,060 more rows</code></pre>
</div>
</div>
<p>There are 1070 entries where the site name or coordinates or both are duplicated.</p>
<p>We have four possible groups based on whether site and/or coordinates are unique:</p>
<table class="table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 60%">
</colgroup>
<thead>
<tr class="header">
<th>Unique site</th>
<th>Unique coordinates</th>
<th>Implication</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>TRUE</td>
<td>TRUE</td>
<td>Data are good to go</td>
</tr>
<tr class="even">
<td>FALSE</td>
<td>TRUE</td>
<td>Multiple locations with single name. This is a problem ; not matchable as is. Coods may have a typo.</td>
</tr>
<tr class="odd">
<td>TRUE</td>
<td>FALSE</td>
<td>Same location with multiple names. Possible name typos. This is not a problem and should be matchable if typo is carried over.</td>
</tr>
<tr class="even">
<td>FALSE</td>
<td>FALSE</td>
<td>Multiple names for same location AND multiple locations for same name</td>
</tr>
</tbody>
</table>
</section>
<section id="duplicated-site-unique-coordinates" class="level4">
<h4 class="anchored" data-anchor-id="duplicated-site-unique-coordinates">Duplicated site; unique coordinates:</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>old_dup <span class="sc">|&gt;</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span>unique_site <span class="sc">&amp;</span> unique_coords</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 793 × 5
# Groups:   lon, lat [793]
   site         lat    lon unique_site unique_coords
   &lt;chr&gt;      &lt;dbl&gt;  &lt;dbl&gt; &lt;lgl&gt;       &lt;lgl&gt;        
 1 Abia        5.72  0.133 FALSE       TRUE         
 2 Abia        5.72  0.132 FALSE       TRUE         
 3 Abia        5.72 -0.133 FALSE       TRUE         
 4 Abidjan     5.33 -4.03  FALSE       TRUE         
 5 Abidjan     5.33 -4.03  FALSE       TRUE         
 6 Abidjan     5.34 -4.03  FALSE       TRUE         
 7 Abuja       9.18  7.17  FALSE       TRUE         
 8 Abuja       9.18  7.17  FALSE       TRUE         
 9 Adibosqual 15.7  38.6   FALSE       TRUE         
10 Adibosqual 15.7  38.6   FALSE       TRUE         
# ℹ 783 more rows</code></pre>
</div>
</div>
<p>So 665 entries have site names associated with &gt;1 sets of coordinates. Some look like typos in the coordinates (e.g., Abia), others look like different nearby locations given the same name (Abuja)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>old_dup <span class="sc">|&gt;</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span>unique_site <span class="sc">&amp;</span> unique_coords</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(site) <span class="sc">|&gt;</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unique</span>() <span class="sc">|&gt;</span></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">length</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 326</code></pre>
</div>
</div>
<p>Of which there are 326 unique site names.</p>
</section>
<section id="unique-site-duplicated-coordinates" class="level4">
<h4 class="anchored" data-anchor-id="unique-site-duplicated-coordinates">Unique site; duplicated coordinates</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>old_dup <span class="sc">|&gt;</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>    unique_site <span class="sc">&amp;</span> <span class="sc">!</span>unique_coords</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(lat, lon)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 200 × 5
# Groups:   lon, lat [111]
   site                     lat   lon unique_site unique_coords
   &lt;chr&gt;                  &lt;dbl&gt; &lt;dbl&gt; &lt;lgl&gt;       &lt;lgl&gt;        
 1 Nkunduze               -27.8  32.2 TRUE        FALSE        
 2 Nkunduzi               -27.8  32.2 TRUE        FALSE        
 3 Opansi                 -27.6  32.3 TRUE        FALSE        
 4 Mahlabaneni            -26.8  31.8 TRUE        FALSE        
 5 Mahlabaneni (Big Bend) -26.8  31.8 TRUE        FALSE        
 6 Mahlabaneni (big bend) -26.8  31.8 TRUE        FALSE        
 7 Luis  cabral           -25.9  32.5 TRUE        FALSE        
 8 Luis Cabral            -25.9  32.5 TRUE        FALSE        
 9 Hectorspruit           -25.4  31.9 TRUE        FALSE        
10 Knp, SKUKUZA           -25.0  31.6 TRUE        FALSE        
# ℹ 190 more rows</code></pre>
</div>
</div>
<p>There are 200 of these which look like they include typos in site names. NB: some must include sites where the name is not unique and location not unique</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>old_dup <span class="sc">|&gt;</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>    unique_site <span class="sc">&amp;</span> <span class="sc">!</span>unique_coords</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(lat, lon)  <span class="sc">|&gt;</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(site) <span class="sc">|&gt;</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unique</span>() <span class="sc">|&gt;</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">length</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 200</code></pre>
</div>
</div>
<p>These make 200 unique names, as expected.</p>
</section>
<section id="duplicated-site-duplicated-coordinates" class="level4">
<h4 class="anchored" data-anchor-id="duplicated-site-duplicated-coordinates">Duplicated site; duplicated coordinates</h4>
<p>Arranged by site name:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>old_dup <span class="sc">|&gt;</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span>unique_site <span class="sc">&amp;</span> <span class="sc">!</span>unique_coords</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(site)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 77 × 5
# Groups:   lon, lat [58]
   site                          lat   lon unique_site unique_coords
   &lt;chr&gt;                       &lt;dbl&gt; &lt;dbl&gt; &lt;lgl&gt;       &lt;lgl&gt;        
 1 Afan-Essokie                2.38  10    FALSE       FALSE        
 2 Agbalilame                  6.38   2.50 FALSE       FALSE        
 3 Agbalilame                  6.4    2.52 FALSE       FALSE        
 4 Ahero                      -0.183 34.9  FALSE       FALSE        
 5 Ambodifotatra &amp; Lonkintsy -17.0   49.9  FALSE       FALSE        
 6 Asembo                     -0.182 34.4  FALSE       FALSE        
 7 Asembo                     -0.182 34.4  FALSE       FALSE        
 8 Asembo                     -0.183 34.4  FALSE       FALSE        
 9 Asembo Bay                 -0.183 34.4  FALSE       FALSE        
10 Asembo Bay                 -0.182 34.4  FALSE       FALSE        
# ℹ 67 more rows</code></pre>
</div>
</div>
<p>And coordinates:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>old_dup <span class="sc">|&gt;</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span>unique_site <span class="sc">&amp;</span> <span class="sc">!</span>unique_coords</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(lat, lon)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 77 × 5
# Groups:   lon, lat [58]
   site                        lat   lon unique_site unique_coords
   &lt;chr&gt;                     &lt;dbl&gt; &lt;dbl&gt; &lt;lgl&gt;       &lt;lgl&gt;        
 1 Ophansi                   -27.6  32.3 FALSE       FALSE        
 2 Komatipoort               -25.4  31.9 FALSE       FALSE        
 3 Knp, Shingwedzi           -23.1  31.4 FALSE       FALSE        
 4 Knp, Shingwedzi           -23.1  31.4 FALSE       FALSE        
 5 Malahlapanga              -22.9  31.0 FALSE       FALSE        
 6 Manarintsoa               -19    47.4 FALSE       FALSE        
 7 Mahazina                  -19.0  47.3 FALSE       FALSE        
 8 Ambodifotatra &amp; Lonkintsy -17.0  49.9 FALSE       FALSE        
 9 Kanyemba                  -15.7  30.3 FALSE       FALSE        
10 Camussamba                -12.8  15.7 FALSE       FALSE        
# ℹ 67 more rows</code></pre>
</div>
</div>
<p>There are 77 of these. Some include Multiple spellings of the name multiple times AND slight variations of coordinates, e.g.&nbsp;Asembo / Asembo Bay.</p>
<p>Some entries will match with entries in other categories, i.e.&nbsp;with unique s have spelling variations that are unique OR coordinates that are unique:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>old_dup <span class="sc">|&gt;</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(site <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Ophansi"</span>, <span class="st">"Opansi"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 5
# Groups:   lon, lat [2]
  site      lat   lon unique_site unique_coords
  &lt;chr&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;lgl&gt;       &lt;lgl&gt;        
1 Opansi  -27.6  32.3 TRUE        FALSE        
2 Ophansi -27.6  32.3 FALSE       TRUE         
3 Ophansi -27.6  32.3 FALSE       FALSE        </code></pre>
</div>
</div>
</section>
<section id="matching" class="level2">
<h2 class="anchored" data-anchor-id="matching">Matching</h2>
<p>Sites, sorted by name in the new database:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>new_sites <span class="ot">&lt;-</span> new_db <span class="sc">|&gt;</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(site, <span class="at">lat =</span> latitude_1, <span class="at">lon =</span> longitude_1) <span class="sc">|&gt;</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>() <span class="sc">|&gt;</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(site)</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>new_sites</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4,110 × 3
   site                                  lat   lon
   &lt;chr&gt;                               &lt;dbl&gt; &lt;dbl&gt;
 1 (El) Thamaniat                     16.0    32.6
 2 10 contiguous villages near Asembo -0.183  34.4
 3 10 villages (50 km NW Kisumu)       0.16   34.4
 4 10 villages near Farafenni         13.6   -15.6
 5 11 contiguous villages near Asembo -0.183  34.4
 6 11 villages (50 km NW Kisumu)       0.16   34.4
 7 12 contiguous villages near Asembo -0.183  34.4
 8 13 contiguous villages near Asembo -0.183  34.4
 9 14 contiguous villages near Asembo -0.183  34.4
10 15 contiguous villages near Asembo -0.183  34.4
# ℹ 4,100 more rows</code></pre>
</div>
</div>
<p><em>(NB: in these data it is evident that there are multiple site names for the same location also in this new database, and multiple locations for the same name)</em></p>
<p>We can prioritise (well, are only interested in) matching the sites with missing coordinates</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>missing_sites <span class="ot">&lt;-</span> new_sites <span class="sc">|&gt;</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">is.na</span>(lat)) <span class="sc">|&gt;</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(site)</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>missing_sites</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 713 × 1
   site                                                                         
   &lt;chr&gt;                                                                        
 1 16 Villages                                                                  
 2 16 villages(Kahoko, Rubirizi, Rwempisi , Kitwe, Nyakafura, Kabimbiri , Bugun…
 3 17 Unspecified villages North of Bo.                                         
 4 31 villages along Malindi, Kilifi, Kwale district coastline                  
 5 32 sites in Cameroon                                                         
 6 Abdel Daiem                                                                  
 7 Abeokuta                                                                     
 8 Abidha_Boi                                                                   
 9 Abidjan                                                                      
10 Abobo (Tegne)                                                                
# ℹ 703 more rows</code></pre>
</div>
</div>
<p>Try matching to <code>old_sites</code> and check how many matches are made.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>site_match <span class="ot">&lt;-</span> missing_sites <span class="sc">|&gt;</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> old_sites,</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">by =</span> <span class="st">"site"</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(site) <span class="sc">|&gt;</span></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>()</span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">|&gt;</span></span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">nmatches =</span> <span class="fu">case_when</span>(</span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a>      <span class="fu">is.na</span>(lat) <span class="sc">~</span> <span class="dv">0</span>,</span>
<span id="cb40-14"><a href="#cb40-14" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> n</span>
<span id="cb40-15"><a href="#cb40-15" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb40-16"><a href="#cb40-16" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb40-17"><a href="#cb40-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>n)</span>
<span id="cb40-18"><a href="#cb40-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-19"><a href="#cb40-19" aria-hidden="true" tabindex="-1"></a>site_match</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 885 × 4
   site                                                       lat   lon nmatches
   &lt;chr&gt;                                                    &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;
 1 16 Villages                                              NA    NA           0
 2 16 villages(Kahoko, Rubirizi, Rwempisi , Kitwe, Nyakafu… NA    NA           0
 3 17 Unspecified villages North of Bo.                     NA    NA           0
 4 31 villages along Malindi, Kilifi, Kwale district coast… NA    NA           0
 5 32 sites in Cameroon                                     NA    NA           0
 6 Abdel Daiem                                              14.5  33.4         1
 7 Abeokuta                                                  7.16  3.35        1
 8 Abidha_Boi                                               NA    NA           0
 9 Abidjan                                                   5.33 -4.03        3
10 Abidjan                                                   5.33 -4.03        3
# ℹ 875 more rows</code></pre>
</div>
</div>
<p>Sites with no match:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>site_match <span class="sc">|&gt;</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(nmatches <span class="sc">==</span> <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 371 × 4
   site                                                       lat   lon nmatches
   &lt;chr&gt;                                                    &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;
 1 16 Villages                                                 NA    NA        0
 2 16 villages(Kahoko, Rubirizi, Rwempisi , Kitwe, Nyakafu…    NA    NA        0
 3 17 Unspecified villages North of Bo.                        NA    NA        0
 4 31 villages along Malindi, Kilifi, Kwale district coast…    NA    NA        0
 5 32 sites in Cameroon                                        NA    NA        0
 6 Abidha_Boi                                                  NA    NA        0
 7 Abobo (Tegne)                                               NA    NA        0
 8 Abu Rakham, Wad Awad, Tenedba                               NA    NA        0
 9 Abu-Eshrin                                                  NA    NA        0
10 Abukako                                                     NA    NA        0
# ℹ 361 more rows</code></pre>
</div>
</div>
<p><strong>371 sites with no matching site name in the old data base.</strong></p>
<p>Sites with multiple matches:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>site_match <span class="sc">|&gt;</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(nmatches <span class="sc">&gt;</span> <span class="dv">1</span>) <span class="sc">|&gt;</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>() <span class="sc">|&gt;</span></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">write_csv</span>(<span class="st">"multiple_matches_20240409.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 264 × 4
   site         lat    lon nmatches
   &lt;chr&gt;      &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;
 1 Abidjan    5.33  -4.03         3
 2 Abidjan    5.33  -4.03         3
 3 Abidjan    5.34  -4.03         3
 4 Aguel-Hoc 19.5    0.854        2
 5 Aguel-Hoc 19.3    0.833        2
 6 Ahero     -0.183 34.9          6
 7 Ahero     -0.182 34.9          6
 8 Ahero     -0.181 34.9          6
 9 Ahero     -0.183 34.9          6
10 Ahero     -0.184 34.9          6
# ℹ 254 more rows</code></pre>
</div>
</div>
<p>264 entries</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>site_match <span class="sc">|&gt;</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(nmatches <span class="sc">&gt;</span> <span class="dv">1</span>) <span class="sc">|&gt;</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(site) <span class="sc">|&gt;</span></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unique</span>() <span class="sc">|&gt;</span></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">length</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 92</code></pre>
</div>
</div>
<p>92 unique site names with multiple sets of coordinates attached.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>